#!/bin/bash
#
# Script para descargar fuentes de Google Fonts en WOFF2
# Usa: goog-webfont-dl (npm package)
#
# Uso:
#   ./download-fonts.sh                    # Usa configuración por defecto
#   ./download-fonts.sh -d ./my-fonts      # Especifica carpeta destino
#   ./download-fonts.sh -c fonts-list.txt  # Especifica archivo de configuración

set -e  # Exit on error

# =============== CONFIGURACIÓN =================

# Carpeta destino para .woff2
FONTS_DIR="./fonts"

# Ruta del archivo CSS
CSS_FILE="./fonts.css"

# Lista de fuentes a descargar (nombre|variantes)
# Formato: "FontName|400,700,700i"
FONTS_LIST=(
    "Roboto|regular,700,700i"
    "Open Sans|400,600,700"
    "Playfair Display|regular,700"
    "Lato|400,700,900"
    "Poppins|300,400,600,700"
)

# =============== FUNCIONES =================

print_header() {
    echo ""
    echo "╔════════════════════════════════════════╗"
    echo "║  🚀 Google Fonts → WOFF2 Downloader   ║"
    echo "╚════════════════════════════════════════╝"
    echo ""
}

print_help() {
    cat << EOF
Uso: $0 [opciones]

Opciones:
  -d, --dir DIR          Carpeta destino para fuentes (default: ./fonts)
  -o, --output FILE      Archivo CSS de salida (default: ./fonts.css)
  -c, --config FILE      Archivo de configuración con lista de fuentes
  -f, --font NAME        Descargar solo una fuente (ej: -f "Roboto")
  -h, --help             Mostrar esta ayuda

Ejemplos:
  $0                                    # Usa configuración por defecto
  $0 -d ./assets/fonts                  # Destino personalizado
  $0 -f "Roboto" -f "Open Sans"         # Múltiples fuentes
  $0 -c mi-fuentes.txt                  # Desde archivo de configuración

Formato archivo de configuración:
  # Comentarios comienzan con #
  Roboto|regular,700,700i
  Open Sans|400,700
  Lato|400,700
EOF
}

load_config_file() {
    local config_file="$1"
    
    if [ ! -f "$config_file" ]; then
        echo "❌ Archivo de configuración no encontrado: $config_file"
        exit 1
    fi
    
    # Limpiar array anterior
    FONTS_LIST=()
    
    # Leer archivo línea por línea
    while IFS= read -r line; do
        # Ignorar líneas vacías y comentarios
        [[ -z "$line" ]] && continue
        [[ "$line" =~ ^# ]] && continue
        
        FONTS_LIST+=("$line")
    done < "$config_file"
    
    echo "✅ Configuración cargada: $config_file (${#FONTS_LIST[@]} fuentes)"
}

check_requirements() {
    echo "📋 Verificando requisitos..."
    
    # Verificar Node.js
    if ! command -v node &> /dev/null; then
        echo "❌ Node.js no instalado. Instálalo en: https://nodejs.org"
        exit 1
    fi
    echo "  ✓ Node.js: $(node --version)"
    
    # Verificar npm
    if ! command -v npm &> /dev/null; then
        echo "❌ npm no instalado"
        exit 1
    fi
    echo "  ✓ npm: $(npm --version)"
    
    # Verificar goog-webfont-dl
    if ! command -v goog-webfont-dl &> /dev/null; then
        echo "  ⚠️  goog-webfont-dl no encontrado. Instalando..."
        npm install -g goog-webfont-dl
    fi
    echo "  ✓ goog-webfont-dl instalado"
    echo ""
}

create_directories() {
    mkdir -p "$FONTS_DIR"
    echo "📁 Carpeta destino: $FONTS_DIR"
}

download_font() {
    local font_spec="$1"
    local font_name="${font_spec%|*}"
    local variants="${font_spec#*|}"
    
    echo "📥 Descargando: $font_name ($variants)..."
    
    # Crear carpeta temporal para esta fuente
    local temp_dir="temp_$(echo $font_name | tr ' ' '_')"
    mkdir -p "$temp_dir"
    
    # Descargar con goog-webfont-dl
    if goog-webfont-dl \
        -f "$font_name" \
        -W \
        -d "$temp_dir" \
        -o "$temp_dir/font.css" 2>/dev/null; then
        
        # Mover archivos .woff2 a carpeta final
        if find "$temp_dir" -name "*.woff2" -type f | while read woff2_file; do
            cp "$woff2_file" "$FONTS_DIR/"
            echo "  ✅ $(basename $woff2_file)"
        done | grep -q "✅"; then
            return 0
        else
            echo "  ⚠️  No se encontraron archivos WOFF2"
            return 1
        fi
    else
        echo "  ❌ Error descargando $font_name"
        return 1
    fi
}

generate_css() {
    echo ""
    echo "🎨 Generando CSS..."
    
    # Iniciar archivo CSS
    {
        echo "/* Generated by Google Fonts Downloader */"
        echo "/* Date: $(date) */"
        echo "/* Total fonts: ${#FONTS_LIST[@]} */"
        echo ""
    } > "$CSS_FILE"
    
    # Buscar todos los archivos WOFF2 y generar @font-face
    for woff2_file in "$FONTS_DIR"/*.woff2; do
        if [ -f "$woff2_file" ]; then
            local filename=$(basename "$woff2_file")
            local font_name="${filename%_*}"
            local variant_part="${filename##*_}"
            
            # Parsear nombre del archivo para obtener peso y estilo
            local weight="400"
            local style="normal"
            
            if [[ "$variant_part" =~ "italic" ]]; then
                style="italic"
                weight=$(echo "$variant_part" | grep -o '[0-9]\+' | head -1)
                [[ -z "$weight" ]] && weight="400"
            else
                weight=$(echo "$variant_part" | grep -o '[0-9]\+' | head -1)
                [[ -z "$weight" ]] && weight="400"
            fi
            
            # Normalizar nombre de fuente
            local font_display_name=$(echo "$font_name" | sed 's/-/ /g' | sed 's/\b./\u&/g')
            
            # Agregar @font-face al CSS
            {
                echo "@font-face {"
                echo "    font-family: '$font_display_name';"
                echo "    src: url('./fonts/$filename') format('woff2');"
                echo "    font-weight: $weight;"
                echo "    font-style: $style;"
                echo "    font-display: swap;"
                echo "}"
                echo ""
            } >> "$CSS_FILE"
        fi
    done
    
    echo "✨ CSS generado: $CSS_FILE"
}

show_summary() {
    echo ""
    echo "╔════════════════════════════════════════╗"
    echo "║          ✅ Descarga completada       ║"
    echo "╚════════════════════════════════════════╝"
    echo ""
    echo "📊 Resumen:"
    echo "  • Carpeta de fuentes: $FONTS_DIR"
    echo "  • Archivos WOFF2: $(find "$FONTS_DIR" -name "*.woff2" | wc -l)"
    echo "  • Archivo CSS: $CSS_FILE"
    echo ""
    echo "📝 Próximos pasos:"
    echo "  1. Incluye $CSS_FILE en tu HTML:"
    echo "     <link rel=\"stylesheet\" href=\"$CSS_FILE\">"
    echo "  2. Usa las fuentes en tu CSS:"
    echo "     body { font-family: 'Roboto', sans-serif; }"
    echo ""
}

# =============== MAIN =================

main() {
    # Parsear argumentos
    while [[ $# -gt 0 ]]; do
        case $1 in
            -d|--dir)
                FONTS_DIR="$2"
                shift 2
                ;;
            -o|--output)
                CSS_FILE="$2"
                shift 2
                ;;
            -c|--config)
                load_config_file "$2"
                shift 2
                ;;
            -f|--font)
                FONTS_LIST=("$2")
                shift 2
                ;;
            -h|--help)
                print_help
                exit 0
                ;;
            *)
                echo "Opción desconocida: $1"
                print_help
                exit 1
                ;;
        esac
    done
    
    # Ejecutar
    print_header
    check_requirements
    create_directories
    
    echo "📋 Fuentes a descargar: ${#FONTS_LIST[@]}"
    echo ""
    
    # Descargar cada fuente
    success_count=0
    for font_spec in "${FONTS_LIST[@]}"; do
        if download_font "$font_spec"; then
            ((success_count++))
        fi
        echo ""
    done
    
    # Generar CSS
    generate_css
    
    # Limpiar carpetas temporales
    rm -rf temp_* 2>/dev/null
    
    # Resumen
    show_summary
    
    echo "✅ $success_count/${#FONTS_LIST[@]} fuentes descargadas correctamente"
}

# Ejecutar main
main "$@"
